# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: "default"
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Abonnement Azure PAYG(1)(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'final'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\Projet final\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\Projet final\azuredeploy.parameters.json'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Abonnement Azure PAYG(0673c009-6d00-4254-9178-35fed48c87be)'
    subscriptionId: '0673c009-6d00-4254-9178-35fed48c87be'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'final'
    location: 'Canada Central'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\Projet final\SA\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\Projet final\SA\azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
